### ISSUE TITLE
на какую версию чит?

### ISSUE THREAD

**Issue by moraz1** [Pan4ur/ThunderHackPlus#12]

**Comment by Pan4ur** [comment]
1.12.2

**Comment by moraz1** [comment]
а как его открыть? просто мне показывает полосу 100% а  гуи не могу открыть

**Comment by Pan4ur** [comment]
.bind clickgui кнопка

**Comment by Pan4ur** [comment]
полоса убирается в Timer -> indicator

**Comment by moraz1** [comment]
чет я не понял где это

**Comment by Pan4ur** [comment]
вкладка мувмент, модуль таймер и в нем

**Comment by moraz1** [comment]
а как NoCom работает?)

**Comment by NCPUser** [comment]
> а как NoCom работает?)
Эксплоит Ищит Игроков На Сервере Во Всех Чанках.

**Comment by NCPUser** [comment]
+Он Юзает Пакеты

**Comment by moraz1** [comment]
понял
