### ISSUE TITLE
Как сделать что-бы работала ливитация

### ISSUE THREAD

**Issue by NCPUser** [Pan4ur/ThunderHackPlus#14]
я тупой или чо как врубить?

**Comment by fdgfhdfhdhth** [comment]
antiBADeffect
ищи там офни и все
саму функцию

**Comment by NCPUser** [comment]
Не Робит.

**Comment by fdgfhdfhdhth** [comment]
тогда не ебу
ты знаеш как панчур из сурсов чит собрал?
