### ISSUE TITLE
JewJew

### ISSUE THREAD

**Issue by ImKindaSus** [Pan4ur/ThunderHackPlus#16]
Добавь локатор похожий на эту гифку
![MERCHANT_DETECTED](https://user-images.githubusercontent.com/72939961/215855971-8e3be84a-5814-4309-bc2c-42d028fede2f.gif)

**Comment by Pan4ur** [comment]
в NoCom или просто как худ?

**Comment by ImKindaSus** [comment]
> в NoCom или просто как худ?
> 
> 

В худ

**Comment by Pan4ur** [comment]
будет в 2.41
