### ISSUE TITLE
Это Слив Или Твой Чит

### ISSUE THREAD

**Issue by NCPUser** [Pan4ur/ThunderHackPlus#3]
Напиши Тут.

**Comment by NCPUser** [comment]
Speed Bind No Work

**Comment by Pan4ur** [comment]
Мой чит

**Comment by Pan4ur** [comment]
Бля забыл про спид, забинди через гуи

**Comment by NCPUser** [comment]
Окей Хорошо Будут Ли Новые Обходы На AAC?

**Comment by Pan4ur** [comment]
Не, я играю онли на сервах дженро (ncp), 2b (strict ncp) и нексусе (matrix)

**Comment by NCPUser** [comment]
На Нексусе Же Был AAC Его Убрали Видимо
