### ISSUE TITLE
ignor creativ mod kill aura

### ISSUE THREAD

**Issue by rusnuker** [Pan4ur/ThunderHackPlus#38]
мне больно смотреть на то, как мои знакомые тщетно, но уверенно пытаются навредить беззащитному еблашку в креативе... так трудно было спиздить одну строчку кода? добавь эту функцию, пожалуйста

**Comment by rusnuker** [comment]
`stream = stream.filter(e -> !( (e instanceof EntityPlayer) && ( ((EntityPlayer)e).isCreative() || ((EntityPlayer)e).isSpectator() ) ));`

**Comment by Pan4ur** [comment]
https://github.com/Pan4ur/ThunderHackPlus/blob/639103b6c20268885eae6103e7cd45a0633c8baa/src/main/java/com/mrzak34/thunderhack/modules/combat/Aura.java#LL632C8-L632C40
Это строка для тебя какая-то шутка??

**Comment by rusnuker** [comment]
:cold_face:

**Comment by rusnuker** [comment]
неужели люди не смотрят в настройки читов? Бля, неужели всем стало вот настолько похер? Поставили конфиг и гоняют с ним, не задумываясь, что там могут быть хорошие функции
