### ISSUE TITLE
Pan4ur

### ISSUE THREAD

**Issue by fdgfhdfhdhth** [Pan4ur/ThunderHackPlus#5]
Привет пан4ур. У меня проблема с вашими сурсами. У меня есть проект, но он не сохраняется проект в чит (в мод jar) Пожалуйста, помогите мне решить это. Спасибо!

**Comment by Pan4ur** [comment]
private String getAnswer( String your_name ){
        if(your_name == "San3km1x"){
            return "iq issue";
        } else {
            return "https://www.youtube.com/watch?v=5dEgxdLUQoI";
        }
    }
