### ISSUE TITLE
bug client

### ISSUE THREAD

**Issue by NCPUser** [Pan4ur/ThunderHackPlus#6]
Im use version 2.38
mod 2.37 WTF
![image](https://user-images.githubusercontent.com/86876065/211852717-dc3e254e-cb47-4097-b1d4-8f077cffa6dd.png)

**Comment by NCPUser** [comment]
И Как Оффнуть Эти Анимации Кушанья От F5?

**Comment by Pan4ur** [comment]
Нельзя отключить 💀

**Comment by NCPUser** [comment]
Окей Хорошо.
