### ISSUE TITLE
Баг Модуля Module,s

### ISSUE THREAD

**Issue by NCPUser** [Pan4ur/ThunderHackPlus#7]
Броня Момент :skull: 
![Uploading 2023-01-11_20.25.43.png…]()

**Comment by NCPUser** [comment]
Ой Бля Models я не так написал

**Comment by Pan4ur** [comment]
Не могу открыть скрин

**Comment by NCPUser** [comment]
Бля ну кароче если одеть броню то она будет на модельки одета странно

**Comment by Pan4ur** [comment]
Ааааа пон

**Comment by Pan4ur** [comment]
я с ноу рендером на броню гоняю, и не замечал

**Comment by NCPUser** [comment]
Пон Я Без NoRender Просто Играю

**Comment by Pan4ur** [comment]
https://github.com/Pan4ur/ThunderHackPlus/releases/tag/2.38
