### ISSUE TITLE
Как двигать ArmorHud в HudEditor

### ISSUE THREAD

**Issue by NCPUser** [Pan4ur/ThunderHackPlus#8]
я просто тупой

**Comment by Pan4ur** [comment]
ThunderGui -> Hud - > ArmorHud -> Position

**Comment by NCPUser** [comment]
Можете сделать чтобы можно ещё в HudEditor менять?

**Comment by Pan4ur** [comment]
Ок

**Comment by Pan4ur** [comment]
https://github.com/Pan4ur/ThunderHackPlus/releases/tag/2.38
